# Generated by Django 3.2.6 on 2021-08-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='contactno',
            new_name='no',
        ),
    ]
